# Generated by Django 3.0.7 on 2020-07-22 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rf_card_number', models.CharField(max_length=150)),
                ('vehicle_id', models.CharField(max_length=100)),
                ('vehicle_reg_number', models.CharField(max_length=150)),
                ('driver_name', models.CharField(blank=True, max_length=150)),
                ('event_date_time', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateField(auto_now_add=True)),
                ('event_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_reg_number', models.CharField(max_length=150, unique=True)),
                ('brand_name', models.CharField(blank=True, max_length=150)),
                ('driver_name', models.CharField(blank=True, max_length=150)),
                ('model', models.CharField(blank=True, max_length=150)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Vehicle_type')),
            ],
        ),
        migrations.CreateModel(
            name='RF_card_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rf_card_number', models.CharField(max_length=150, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_status', models.IntegerField(default=0)),
                ('vehicle_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Vehicle_info')),
            ],
        ),
    ]
