# Generated by Django 3.0.7 on 2020-07-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rf_card_info_vehicle_info_vehicle_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_log',
            name='event_type',
            field=models.IntegerField(default=0),
        ),
    ]
